// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    ext.kotlin_version = '1.6.10'
    ext.safeargs_version = '2.4.1'
    System.properties['com.android.build.gradle.overrideVersionCheck'] = 'true'
    repositories {
        google()
        mavenCentral()
        maven { url "https://plugins.gradle.org/m2/" }
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "androidx.navigation:navigation-safe-args-gradle-plugin:$safeargs_version"
        classpath("org.jetbrains.dokka:dokka-gradle-plugin:1.4.32")

        // TODO AC-861
        //classpath 'com.dicedmelon.gradle:jacoco-android:0.1.4'
        classpath "com.hiya:jacoco-android:0.2"

        // Hilt Plugin
        classpath 'com.google.dagger:hilt-android-gradle-plugin:2.42'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://yanzm.github.io/MaterialTabHost/repository' }
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
        jcenter()
        maven { url "https://jitpack.io" }
    }
}
